@extends('layout')

@section('content')
    <section id="main-container" class="main-container">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h3>The Pyrum Thermolysis</h3>
                    <p>The unique Pyrum-Thermolysis is a thermal dismantling of organic substances respectively rubber and plastic waste under exclusion of oxygen. The process allows precise temperature and pressure control, which minimizes the risks during the pyrolysis process (spark-free and airtight) and guarantees raw materials of a constant, high quality. These process conditions produce vapors that condense to oil at low temperatures, permanent gas (gaseous hydrocarbon compounds) and coke.</p>
                    <p>A special feature of the patented process is that, after a single start-up of the plant with external energy, sufficient energy is generated by the recovered gas to enable self-sufficient operation of the plant. In addition, a surplus of energy is won, which can be resold as thermal or electrical energy.</p>
                    <p>The Pyrum technology can process the following waste and input materials:</p>
                    <ul>
                        <li><b>Used tires</b> (cars, trucks, motorcycles, construction machinery, etc.)</li>
                        <li><b>Bitumen mats and isolations</b> (e.g. roofing felt made of bitumen)</li>
                        <li><b>EPDM and other elastomer rubber waste</b> (window and door isolations)</li>
                        <li><b>PE/PET (films, bottles, moulded parts, etc.)</b></li>
                        <li><b>Oil shale and oil sands (in test phase)</b></li>
                    </ul>
                    <p>The following products can be generated with this process: <b>rubber flour, soot, coke, activated charcoal, crude oils, gas (like natural gas), electricity and waste heat.</b></p>

                    <p>
                        The disposal of rubber and plastic waste will be of considerable importance in the coming years, as the disposal methods used up to now have been very harmful to the environment. For example, the disposal of used tires in cement plants is to be banned until 2025. In addition, tire manufacturers like Michelin have the goal of producing a large proportion of tires from recycled raw materials in the future. In this respect, the innovative recycling process being used is particularly well suited to serve as an example of a future-oriented waste management concept. It combines economic and ecological requirements for a waste management concept with low investment and operating costs, serves to recover raw materials and substitutes fossil fuels.
                    </p>
                </div><!-- Col end -->

                <div class="col-md-6">
                    <h3>Procedure</h3>
                    <p>The applied thermolysis recycling process has multiple stages.</p>
                    <h4>Step 1</h4>
                    <ul>
                        <li>Fragmentation (shredding) of the input material into granules from 1 to 12 mm</li>
                        <li>Separation of metal and textile parts for reuse</li>
                    </ul>

                    <h4>Step 2</h4>
                    <ul>
                        <li>Thermolysis of the rubber granulate in the patented vertical reactor</li>
                        <li>Separation of the resulting products steam and coke</li>
                    </ul>

                    <h4>Step 3</h4>
                    <ul>
                        <li>Condensation of the vapors</li>
                        <li>Separation of oil and permanent gas</li>
                    </ul>

                    <h4>Step 4</h4>
                    <ul>
                        <li>Cooling of the coke</li>
                        <li>Grinding, sifting, classification and pelleting of the coke into commercial products: Industrial carbon black, rCB (recovered Carbon Black)</li>
                    </ul>

                    <h4>Step 5</h4>
                    <p>Power generation for main and auxiliary aggregates</p>
                    <ul>
                        <li>Recuperation (recovery) of exhaust gas energy</li>
                        <li>Generation of electrical energy for self-sufficiency and sale with the help of a combined heat and power unit</li>
                    </ul>

                    <h4>Step 6</h4>
                    <ul>
                        <li>Rectification of the oil</li>
                        <li>Storage of the various oil types in the tank farm</li>
                    </ul>

                    <h4>Step 7</h4>
                    <ul>
                        <li>Purification of the exhaust air of the combined heat and power unit to the legally prescribed limits. The actual Pyrum Thermolysis process does not produce any exhaust gases, only the CHP produces small amounts.</li>
                    </ul>

                    <h4>Step 8</h4>
                    <p>Refinement of the intermediate products: Heat, oil and coke, for example:</p>
                    <ul>
                        <li>Combined heat and power generation with residents</li>
                        <li>Carbon black production from oilProduction of activated charcoal from coke</li>
                    </ul>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <h2>Scheme 1: The Pyrum Thermolysis</h2>
                </div><!-- Col end -->
                <div class="col-md-8">
                    <img src="/assets/images/production-process.jpg" style="width: 90%; margin-left: 5px;"/>
                </div>
                <div class="col-md-4">
                    <h4>Legend</h4>
                    <p>1: Shredding of the rubber granulate up to 12 mm grain size</p>
                    <p>2: Pyrum thermolysis reactor. Separates the rubber granulate into steam and solid matter.</p>
                    <p>3: Vertical cooler for solids</p>
                    <p>4: Steam condensation to oil and gas</p>
                    <p>5: CHP for power generation</p>
                    <img src="/assets/images/status-process.jpg" style="width: 80%; margin-left: 10%;"/>
                </div>
            </div><!-- Content row end -->
        </div><!-- Conatiner end -->
    </section><!-- Main container end -->
@endsection
